
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMENTARIO_HTML ETIQUETA_APERTURA ETIQUETA_CIERRE TEXTOdocumento : elementoselementos : elementos elementoelementos : elementoelemento : ETIQUETA_APERTURA elementos ETIQUETA_CIERREelemento : TEXTOelemento : COMENTARIO_HTML'
    
_lr_action_items = {'ETIQUETA_APERTURA':([0,2,3,4,5,6,7,8,9,],[4,4,-3,4,-5,-6,-2,4,-4,]),'TEXTO':([0,2,3,4,5,6,7,8,9,],[5,5,-3,5,-5,-6,-2,5,-4,]),'COMENTARIO_HTML':([0,2,3,4,5,6,7,8,9,],[6,6,-3,6,-5,-6,-2,6,-4,]),'$end':([1,2,3,5,6,7,9,],[0,-1,-3,-5,-6,-2,-4,]),'ETIQUETA_CIERRE':([3,5,6,7,8,9,],[-3,-5,-6,-2,9,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'documento':([0,],[1,]),'elementos':([0,4,],[2,8,]),'elemento':([0,2,4,8,],[3,7,3,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> documento","S'",1,None,None,None),
  ('documento -> elementos','documento',1,'p_documento','parser_ply.py',20),
  ('elementos -> elementos elemento','elementos',2,'p_elementos_lista','parser_ply.py',26),
  ('elementos -> elemento','elementos',1,'p_elementos_uno','parser_ply.py',31),
  ('elemento -> ETIQUETA_APERTURA elementos ETIQUETA_CIERRE','elemento',3,'p_elemento_etiqueta','parser_ply.py',35),
  ('elemento -> TEXTO','elemento',1,'p_elemento_texto','parser_ply.py',43),
  ('elemento -> COMENTARIO_HTML','elemento',1,'p_elemento_comentario','parser_ply.py',47),
]
